### ISSUE TITLE
Only persistent Thunderbird notifications?

### ISSUE THREAD

**Issue by Filbuntu** [fthx/persistent-email-notifications#1]
Thanks again for telling me about this extension and creating it!
If I like to only have persistent notification for Thunderbird, I guess I can change the following line in the extension.js (/home/cds/.local/share/gnome-shell/extensions/persistent-email-notifications@fthx), right?

`var EMAIL_APP_NAMES = [ "Thunderbird", "Evolution", "Mailspring", "Geary" ];`

**Comment by fthx** [comment]
Yes it contains all the apps for which you want persistent notifications. You can include any other app too! ;-) 
So just removing "Evolution", "Mailspring", "Geary" is right for you.
