### ISSUE TITLE
Could you please add typeapp mail client support

### ISSUE THREAD

**Issue by foreignerby** [fthx/persistent-email-notifications#2]
Hi,

Could you please add typeapp mail client support:
[https://snapcraft.io/typeapp-mail](https://snapcraft.io/typeapp-mail)
By the way, I can't add typeapp snap application as a default mail application in gnome-shell settings, maybe this is my issue

**Comment by fthx** [comment]
My other email extension:
https://extensions.gnome.org/extension/1505/new-mail-indicator/
does detect the default email app.

But you're lucky, this one simply has an email apps list. So let's try this:
https://github.com/fthx/persistent-email-notifications/commit/f16f6bdc74d9701023d24d5de7046ce9d60f994b
I'm not sure if the name is correct ("TypeApp"). Tell me.

Feel free to reopen if this does not work (after restarting your session).

**Comment by fthx** [comment]
Wow, it has already been reviewed!!
So you should have an extension update through the usual GNOME way.

**Comment by foreignerby** [comment]
I think my problem is that I can't define TypeApp as my default mail app in gnome-shell settings.
I have only Geary in this drop-down menu. Could you please advise how to fix this?
![image](https://user-images.githubusercontent.com/80088469/115997152-ce7a8b80-a5ea-11eb-9265-45fba78df923.png)

**Comment by fthx** [comment]
You have to address this to TypeApp maintainers. They have to declare their app as email-capable.
Nonetheless, this does not interfere with this extension's way. So, does the new extension version work?

**Comment by foreignerby** [comment]
Yes. It works perfect now! Thank you very much!
Do I have any possibility to donate your work? ))

**Comment by fthx** [comment]
That's nice but I don't make extensions for money.
And this one is a very small one.

Did you try BaBar?
30 % off to subscription if you install BaBar. ^_^
