### ISSUE TITLE
Could you please add bluemail client support

### ISSUE THREAD

**Issue by foreignerby** [fthx/persistent-email-notifications#3]
Hi,

Could you please add one more mail client support(bluemail):
https://www.bluemail.me/

**Comment by fthx** [comment]
Hi,

I need the notification displayed when you receive a new mail.

**Comment by foreignerby** [comment]
I see the standard Gnome notification:
![bluemail](https://user-images.githubusercontent.com/80088469/122684872-cf0d5800-d210-11eb-9287-c98c5fd62c1c.png)

**Comment by fthx** [comment]
You can try to add "Bluemail" or "BlueMail" to app list in extension.js to see the exact app name?
Tell me which one works.

**Comment by foreignerby** [comment]
This option works:
`var EMAIL_APP_NAMES = [ "Thunderbird", "Evolution", "Mailspring", "Geary", "TypeApp", "BlueMail" ];`
Thank you!

**Comment by fthx** [comment]
Ok, that's changed and uploaded.
